### ISSUE TITLE
Lecture 12 Cache Memories.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#11]
* Markdown 文件：[Lecture 12 Cache Memories.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2012%20%20Cache%20Memories.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huqianshan** [comment]
申请翻译

**Comment by EugeneLiu** [comment]
认领成功 @huqianshan

**Comment by EugeneLiu** [comment]
@huqianshan 同学，lecture 12 翻译完成了吗？
