### ISSUE TITLE
Lecture 13 Linking.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#12]
* Markdown 文件：[Lecture 13 Linking.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2013%20%20Linking.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by redtecher** [comment]
申请翻译

**Comment by EugeneLiu** [comment]
认领成功 @redtecher

**Comment by redtecher** [comment]
@EugeneLiu    翻译过程中 发现英文字幕有问题直接修改吗

**Comment by leviding** [comment]
@EugeneLiu 可以的，是应该修改

**Comment by EugeneLiu** [comment]
@redtecher 英文字幕只有 90% 的正确率，如果发现错误可以直接修改。

**Comment by EugeneLiu** [comment]
@redtecher 视频已经压制并上传，[B站地址](https://www.bilibili.com/video/av31289365/?p=7)，再次感谢参与。
