### ISSUE TITLE
Lecture 15 Exceptional Control Flow Signals and Nonlocal Jumps.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#14]
* Markdown 文件：[Lecture 15 Exceptional Control Flow Signals and Nonlocal Jumps.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2015%20%20Exceptional%20Control%20Flow%20%20Signals%20and%20Nonlocal%20Jumps.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MRNIU** [comment]
@leviding 翻译认领

**Comment by EugeneLiu** [comment]
认领成功 @MRNIU

**Comment by MRNIU** [comment]
@EugeneLiu 翻译完成
