### ISSUE TITLE
Lecture 16 System Level I_O.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#15]
* Markdown 文件：[Lecture 16 System Level I_O.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2016%20System%20Level%20I_O.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xqitong** [comment]
翻译认领

**Comment by leviding** [comment]
@xqitong 好的

**Comment by EugeneLiu** [comment]
@xqitong 同学你的翻译开始了吗？

**Comment by xqitong** [comment]
> @xqitong 同学你的翻译开始了吗？

已经翻了600多行了，感觉有点慢

**Comment by EugeneLiu** [comment]
> > @xqitong 同学你的翻译开始了吗？
> 
> 已经翻了600多行了，感觉有点慢

可以使用机器翻译来辅助翻译

**Comment by xqitong** [comment]
好的，明白了，谢谢



发自我的小米Pad
在 Eugene <notifications@github.com>，2019年3月10日 下午10:01写道：

@xqitong<https://github.com/xqitong> 同学你的翻译开始了吗？

已经翻了600多行了，感觉有点慢

可以使用机器翻译来辅助翻译
