### ISSUE TITLE
Lecture 17 Virtual Memory Concepts.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#16]
* Markdown 文件：[Lecture 17 Virtual Memory Concepts.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2017%20%20Virtual%20Memory%20%20Concepts.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yetiancn** [comment]
翻译认领 @EugeneLiu

**Comment by leviding** [comment]
@yetiancn 好滴~

**Comment by EugeneLiu** [comment]
@yetiancn 同学你开始翻译了吗？

**Comment by yetiancn** [comment]
抱歉有延误，已经开始，将尽快完成

**Comment by yetiancn** [comment]
Finished.
