### ISSUE TITLE
Lecture 02 Bits, Bytes, and Integers.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#17]
Lecture 02 翻译完成，现在需要招募校对人员。
字幕地址：[Lecture 02 Bits, Bytes, and Integers.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2002%20%20Bits%2C%20Bytes%2C%20and%20Integers.ass)

**Comment by Jinzhengxu** [comment]
@EugeneLiu 校对认领

**Comment by Jinzhengxu** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
认领成功啦
