### ISSUE TITLE
Lecture 03 Bits, Bytes, and Integers cont.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#18]
字幕地址：[Lecture 03 Bits, Bytes, and Integers cont.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2003%20%20Bits%2C%20Bytes%2C%20and%20Integers%20cont.ass)

**Comment by tutaizi** [comment]
@leviding 认领校对

**Comment by leviding** [comment]
@tutaizi 👌
