### ISSUE TITLE
Lecture 04 Floating Point.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#19]
字幕文件地址：[Lecture 04 Floating Point.ass
](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2004%20%20Floating%20Point.ass)

**Comment by rosaline1995** [comment]
@leviding 认领校对。

**Comment by EugeneLiu** [comment]
@rosaline1995 认领成功

**Comment by zhangliang1997** [comment]
认领校对

**Comment by zhangliang1997** [comment]
> 字幕文件地址：[Lecture 04 Floating Point.ass ](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2004%20%20Floating%20Point.ass)

认领校对

**Comment by zhangliang1997** [comment]
@leviding  认领校对

**Comment by zhangliang1997** [comment]
@EugeneLiu  认领校对

**Comment by EugeneLiu** [comment]
@zhangliang1997 认领成功，期待你的提交。
