### ISSUE TITLE
Lecture 07 Machine Level Programming III Procedures.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#23]
字幕地址：[Lecture 07 Machine Level Programming III Procedures.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2007%20%20Machine%20Level%20Programming%20III%20%20Procedures.ass)

**Comment by pkuwwt** [comment]
申请校对 @EugeneLiu

**Comment by EugeneLiu** [comment]
认领成功 @pkuwwt

**Comment by MRNIU** [comment]
申请校对 @EugeneLiu

**Comment by pkuwwt** [comment]
@EugeneLiu 校对完。主要是重新翻译了中文。https://github.com/EugeneLiu/translationCSAPP/pull/26

**Comment by EugeneLiu** [comment]
@pkuwwt 幸苦了，🙏
