### ISSUE TITLE
Lecture 08 Machine Level Programming IV Data.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#24]
字幕地址：[Lecture 08 Machine Level Programming IV Data.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2008%20%20Machine%20Level%20Programming%20IV%20%20Data.ass)

**Comment by MRNIU** [comment]
申请校对 @EugeneLiu

**Comment by EugeneLiu** [comment]
@MRNIU 认领成功
