### ISSUE TITLE
Lecture 06 翻译认领

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#28]
[Lecture 06 Machine Level Programming II Control.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2006%20%20Machine%20Level%20Programming%20II%20%20Control.ass)

**Comment by muzea** [comment]
申请翻译 @EugeneLiu

**Comment by EugeneLiu** [comment]
认领成功

**Comment by zhangliang1997** [comment]
申请翻译 @EugeneLiu

**Comment by FrogLu** [comment]
申请翻译 @EugeneLiu

**Comment by EugeneLiu** [comment]
@FrogLu 同学正在校对
