### ISSUE TITLE
Lecture 18 Virtual Memory Systems.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#33]
* 英文 ass 文件：[Lecture 18 Virtual Memory Systems.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2018%20%20Virtual%20Memory%20%20Systems.ass)
  * 机器翻译字幕：[Lecture 18 Virtual Memory Systems.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/Chinese_English/Lecture%2018%20%20Virtual%20Memory%20%20Systems.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：15 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fxrc2018** [comment]
翻译认领

**Comment by EugeneLiu** [comment]
@fxrc2018 认领成功
