### ISSUE TITLE
Lecture 20 Dynamic Memory Allocation Advanced Concepts.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#35]
* 英文 ass 文件：[Lecture 20 Dynamic Memory Allocation Advanced Concepts.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2020%20%20Dynamic%20Memory%20Allocation%20%20Advanced%20Concepts.ass)
  * 机器翻译字幕：[Lecture 20 Dynamic Memory Allocation Advanced Concepts.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/Chinese_English/Lecture%2020%20%20Dynamic%20Memory%20Allocation%20%20Advanced%20Concepts.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：15 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EugeneLiu** [comment]
@CynricFeng

**Comment by 761929351** [comment]
校对

**Comment by EugeneLiu** [comment]
@761929351 申请成功
