### ISSUE TITLE
Lecture 22 Network Programming Part II.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#37]
* 英文 ass 文件：[Lecture 22 Network Programming Part II.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2022%20%20Network%20Programming%20%20Part%20II.ass)
  * 机器翻译字幕：[Lecture 22 Network Programming Part II.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/Chinese_English/Lecture%2022%20%20Network%20Programming%20%20Part%20II.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：15 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zkangHUST** [comment]
申请翻译 @EugeneLiu

**Comment by EugeneLiu** [comment]
认领成功 @zkangHUST

**Comment by EugeneLiu** [comment]
@zkangHUST 同学不要忘记你的翻译任务哈

**Comment by EugeneLiu** [comment]
@zkangHUST 同学，你的认领的任务翻译完了吗？

**Comment by CNYuYang** [comment]
申请翻译

**Comment by EugeneLiu** [comment]
@Reyunn 认领成功

**Comment by linzissu** [comment]
申请翻译
