### ISSUE TITLE
Lecture 09 Machine Level Programming V Advanced Topics.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#46]
字幕地址：[Lecture 09 Machine Level Programming V Advanced Topics.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2009%20%20Machine%20Level%20Programming%20V%20%20Advanced%20Topics.ass)

**Comment by Maecenas** [comment]
申请校对 @EugeneLiu

**Comment by EugeneLiu** [comment]
认领成功 @Maecenas

**Comment by good1uck** [comment]
申请校对 @EugeneLiu
