### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fxrc2018** [EugeneLiu/translationCSAPP#49]
- 公司/学校：重庆邮电大学
- 工作内容/专业：电子科学与技术
- 常浏览的国外网站：Youtobe
- 英语水平：\
- 翻译经验：\
- 主要翻译方向：\
- 个人博客：\
- 个人介绍：想让更多的人学习这门课程

**Comment by EugeneLiu** [comment]
欢迎加入
