### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZCplayground** [EugeneLiu/translationCSAPP#54]
- 学校：福州大学
- 专业：CS
- 常浏览的国外网站：YouTube、Google、Stackoverflow、Twitter
- 英语水平：CET6 557分，正在学习托福
- 翻译经验：曾经做过B站的野生弹幕君，[这个视频](https://www.bilibili.com/video/av23570048?p=1)的1p和2p下面的字幕就是我做的。
- 主要翻译方向：无
- 个人博客：https://www.cnblogs.com/ZCplayground/category/956963.html
- 个人介绍：在2017年的时候我自学了CSAPP这本书，自己对英语也比较感兴趣，想利用业余时间做一集字幕，算是一件有意义的事情。

**Comment by EugeneLiu** [comment]
申请成功，直接在「翻译认领」标签下面回复就可以申请翻译。我们还有一个 QQ 群，818970413，欢迎加入我们。
