### ISSUE TITLE
Lecture 10 Program Optimization.ass

### ISSUE THREAD

**Issue by EugeneLiu** [EugeneLiu/translationCSAPP#55]
* Markdown 文件：[Lecture 10 Program Optimization.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2010%20%20Program%20Optimization.ass)

  ----
  * 翻译时间：15 天
  * 校对时间：7 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fxrc2018** [comment]
翻译认领

**Comment by EugeneLiu** [comment]
@fxrc2018 认领成功

**Comment by EugeneLiu** [comment]
@fxrc2018 同学字幕翻译不要忘记了
