### ISSUE TITLE
文件夹说明

### ISSUE THREAD

**Issue by stardustman** [EugeneLiu/translationCSAPP#64]
可以说明一下,每一个文件夹都是什么类型的字幕吗?哪一些是已经校对的成品.

**Comment by stardustman** [comment]
translation是已经校对好的吗?

**Comment by EugeneLiu** [comment]
English 校对过的英文字幕，Chiese_English 校对过的英文字幕和机翻中文字幕，translation 放的是最后翻译和校对完成的字幕。

**Comment by yuanzhoucq** [comment]
> English 校对过的英文字幕，Chiese_English 校对过的英文字幕和机翻中文字幕，translation 放的是最后翻译和校对完成的字幕。

如果在B站看视频的时候发现一些小的错误想要提交 PR 修改的话，应该改哪个文件夹的文件呢？
