### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhangliang1997** [EugeneLiu/translationCSAPP#66]
- 公司/学校：南京邮电大学/国防科技大学
- 工作内容/专业：体系结构
- 常浏览的国外网站：GitHub，StackOverflow
- 英语水平：过六级
- 翻译经验：一直阅读英文原版技术书籍
- 主要翻译方向：计算机相关技术
- 个人博客：无
- 个人介绍：吃吃喝喝到处逛

**Comment by EugeneLiu** [comment]
申请成功，欢迎参与字幕的制作。
