### ISSUE TITLE
Lecture 05 Machine Level Programming I 原文-翻译对不上

### ISSUE THREAD

**Issue by fizermire** [EugeneLiu/translationCSAPP#68]
Line 338
Dialogue: 0,0:12:20.88,0:12:25.66,English,,0,0,0,,I think the the shark machines or approximately that same **area**
Dialogue: 0,0:12:20.88,0:12:25.66,Chinese,,0,0,0,,我认为是鲨鱼机器或差不多时代的东西

这里的area(位置？)听读音应该是era(时代)，对应中文是时代是没错的，但是对应的英文可能不正确。

**Comment by EugeneLiu** [comment]
感谢你的反馈🙂
