### ISSUE TITLE
Lecture 09 Machine Level Programming V Advanced Topics.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#8]
* Markdown 文件：[Lecture 09 Machine Level Programming V Advanced Topics.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2009%20%20Machine%20Level%20Programming%20V%20%20Advanced%20Topics.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by maconn** [comment]
@EugeneLiu 校对认领

**Comment by EugeneLiu** [comment]
@maconn 认领成功
