### ISSUE TITLE
Lecture 10 Program Optimization.ass

### ISSUE THREAD

**Issue by leviding** [EugeneLiu/translationCSAPP#9]
* Markdown 文件：[Lecture 10 Program Optimization.ass](https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2010%20%20Program%20Optimization.ass)
  * PR 地址：
  **注意**：翻译之前请先结合视频校对英文字幕是否有误，如有误，请先修正并 PR，修改 merge 之后再进行字幕翻译，翻译完成进行 PR，有问题随时联系 @leviding 。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lotdoney** [comment]
申请翻译

**Comment by lotdoney** [comment]
@leviding

**Comment by EugeneLiu** [comment]
@lotdoney 认领成功

**Comment by lotdoney** [comment]
Thanks for your agreement ，I will translate my task immediately。

**Comment by EugeneLiu** [comment]
@lotdoney 同学你的翻译开始了吗？

**Comment by EugeneLiu** [comment]
@lotdoney 同学你的翻译开始了吗？
