### ISSUE TITLE
关于 lab 下载问题

### ISSUE THREAD

**Issue by pedrogao** [EugeneLiu/translationCSAPP#99]
csapp lab 现在必须申请 account 才能下载使用，且申请 account 必须是教育邮箱，且大学是全英文主页，无疑阻挡了很多国人学习的脚步，有人可以将 Labs 下载下来然后上传到这个仓库吗，拜谢了~

**Comment by FrogLu** [comment]
> csapp lab 现在必须申请 account 才能下载使用，且申请 account 必须是教育邮箱，且大学是全英文主页，无疑阻挡了很多国人学习的脚步，有人可以将 Labs 下载下来然后上传到这个仓库吗，拜谢了~

传到公开仓库估计不行，license可能不允许，我私发你邮箱吧

**Comment by pedrogao** [comment]
> > csapp lab 现在必须申请 account 才能下载使用，且申请 account 必须是教育邮箱，且大学是全英文主页，无疑阻挡了很多国人学习的脚步，有人可以将 Labs 下载下来然后上传到这个仓库吗，拜谢了~
> 
> 传到公开仓库估计不行，license可能不允许，我私发你邮箱吧

1312342604@qq.com，多谢啦~

**Comment by Waldenth** [comment]
> csapp lab 现在必须申请 account 才能下载使用，且申请 account 必须是教育邮箱，且大学是全英文主页，无疑阻挡了很多国人学习的脚步，有人可以将 Labs 下载下来然后上传到这个仓库吗，拜谢了~

不需要吧
[csappLab](http://csapp.cs.cmu.edu/3e/labs.html)
只需要下载writeup和self-study-handout不就可以了吗

**Comment by spike014** [comment]
> > csapp lab 现在必须申请 account 才能下载使用，且申请 account 必须是教育邮箱，且大学是全英文主页，无疑阻挡了很多国人学习的脚步，有人可以将 Labs 下载下来然后上传到这个仓库吗，拜谢了~
> 
> 传到公开仓库估计不行，license可能不允许，我私发你邮箱吧

你好，请问能发一份给我吗，链接似乎是失效了？l1ng14<at>foxmail.com 如果可以的话，万分感谢。
